/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.Ingrediente;
import com.mycompany.restaurantedtos.ActualizarIngredienteDTO;
import com.mycompany.restaurantenegocio.NegocioException;
import com.mycompany.restaurantenegocio.ObjetosBoDTO;
import interfaces.SeleccionIngredienteListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class FrmAgregarStockIngrediente extends javax.swing.JFrame implements SeleccionIngredienteListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAgregarStockIngrediente.class.getName());
    private Ingrediente ingredienteSeleccionado;
    private ObjetosBoDTO objetosBO;
    
    /**
     * Creates new form FrmAgregarStockIngrediente
     */
    public FrmAgregarStockIngrediente(ObjetosBoDTO objetosBO) {
        this.objetosBO = objetosBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtNombreIngrediente = new javax.swing.JTextField();
        lblNombreIngrediente = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        txtUnidadMedida = new javax.swing.JTextField();
        lblStockActual = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        lblStockAAgregar = new javax.swing.JLabel();
        txtCantidadAAgregar = new javax.swing.JTextField();
        btnAgregarStock = new javax.swing.JButton();
        btnVovler = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(67, 82, 90));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Ingredientes -- Agregar Stock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(183, 183, 183))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(33, 84, 164));
        lblTitulo2.setText("Agregar Stock a Ingrediente");

        txtNombreIngrediente.setEditable(false);
        txtNombreIngrediente.setForeground(new java.awt.Color(0, 0, 0));

        lblNombreIngrediente.setText("Nombre:");

        lblUnidadMedida.setText("Unidad de Medida");

        txtUnidadMedida.setEditable(false);
        txtUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));

        lblStockActual.setText("Stock actual: ");

        txtStockActual.setEditable(false);
        txtStockActual.setForeground(new java.awt.Color(0, 0, 0));

        lblStockAAgregar.setText("Cantidad a agregar:");

        txtCantidadAAgregar.setForeground(new java.awt.Color(0, 0, 0));

        btnAgregarStock.setBackground(new java.awt.Color(0, 128, 0));
        btnAgregarStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarStock.setText("Agregar");
        btnAgregarStock.addActionListener(this::btnAgregarStockActionPerformed);

        btnVovler.setBackground(new java.awt.Color(66, 66, 66));
        btnVovler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVovler.setForeground(new java.awt.Color(255, 255, 255));
        btnVovler.setText("Volver");
        btnVovler.addActionListener(this::btnVovlerActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(23, 117, 209));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnidadMedida)
                            .addComponent(lblNombreIngrediente)
                            .addComponent(lblStockActual)
                            .addComponent(lblStockAAgregar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreIngrediente)
                            .addComponent(txtUnidadMedida)
                            .addComponent(txtStockActual)
                            .addComponent(txtCantidadAAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVovler)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(257, 257, 257))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreIngrediente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadMedida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockActual))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadAAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockAAgregar))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarStock)
                .addGap(60, 60, 60)
                .addComponent(btnVovler)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        FrmBuscadorIngredientes frame = new FrmBuscadorIngredientes(objetosBO,this);
        frame.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
       this.actualizarStockIngrediente();
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnVovlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVovlerActionPerformed
        this.vaciarForm();
        this.dispose();
        FrmSeleccionarOpcionIngrediente frame = new FrmSeleccionarOpcionIngrediente(objetosBO);
        frame.setVisible(true);
    }//GEN-LAST:event_btnVovlerActionPerformed
    
    private void actualizarStockIngrediente(){
        try {
            if (ingredienteSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Selecciona un ingrediente primero");
                return;
            }
            int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea agregar el stock al ingrediente?",
                "Confirmar agregar stock",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );
            if(opcion == JOptionPane.YES_OPTION){
                Long idIngrediente = this.ingredienteSeleccionado.getId();
                Integer cantidadAAgregar = Integer.valueOf(txtCantidadAAgregar.getText());
                ActualizarIngredienteDTO ingrediente = new ActualizarIngredienteDTO(idIngrediente,cantidadAAgregar);
                Ingrediente ingredienteActualizado = objetosBO.getIngredientesBO().agregarStockIngrediente(ingrediente);
                String mensaje = """
                            ¡Stock Ingrediente Actualizado Correctamente!
                             ID Ingrediente:  """+ingredienteActualizado.getId()+
                            "\n"+"Nombre: "+ingredienteActualizado.getNombre()+
                            "\n"+"Stock Actualizado: "+ingredienteActualizado.getStock();
                JOptionPane.showMessageDialog(this, mensaje,"Ingrediente Actualizado Correctamente.",JOptionPane.INFORMATION_MESSAGE);
                vaciarForm();
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error al actualizar el stock.\n Se espera un numero enetero positivo. ","ERROR",JOptionPane.ERROR_MESSAGE);
        }catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el ingrediente: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void vaciarForm(){
        txtNombreIngrediente.setText("");
        txtStockActual.setText("");
        txtUnidadMedida.setText("");
        txtCantidadAAgregar.setText("");
        this.ingredienteSeleccionado = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVovler;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreIngrediente;
    private javax.swing.JLabel lblStockAAgregar;
    private javax.swing.JLabel lblStockActual;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JTextField txtCantidadAAgregar;
    private javax.swing.JTextField txtNombreIngrediente;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ingredienteSeleccionado(Ingrediente ingredienteSeleccionado) {
        this.ingredienteSeleccionado = ingredienteSeleccionado;
        txtNombreIngrediente.setText(ingredienteSeleccionado.getNombre());
        txtStockActual.setText(String.valueOf(ingredienteSeleccionado.getStock()));
        txtUnidadMedida.setText(ingredienteSeleccionado.getUnidadMedida().toString());
    }
}
