
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.Ingrediente;
import com.mycompany.restaurantedtos.BuscadorIngredientesDTO;
import com.mycompany.restaurantedtos.ReporteClientesFrecuentesDTO;
import com.mycompany.restaurantedtos.UnidadMedida;
import com.mycompany.restaurantenegocio.IIngredientesBO;
import com.mycompany.restaurantenegocio.NegocioException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian
 */
public class FrmBuscadorIngredientes extends javax.swing.JFrame {
    private IIngredientesBO ingredientesBO;
    private List<Ingrediente> ingredientesActuales;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscadorIngredientes.class.getName());

    /**
     * Creates new form FrmBuscadorIngredientes
     * @param ingredientesBO
     */
    public FrmBuscadorIngredientes(IIngredientesBO ingredientesBO) {
        this.ingredientesBO = ingredientesBO;
        initComponents();
        this.inicializarTablaLlena();
        this.llenarComboUnidadMedida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblFiltroNombre = new javax.swing.JLabel();
        txtFiltroNombre = new javax.swing.JTextField();
        comboUnidadMedida = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();
        lblUnidadMedida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVovler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(67, 82, 90));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Ingredientes -- Buscador Ingredientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(33, 84, 164));
        lblTitulo2.setText("Buscador Ingredientes");

        lblFiltroNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFiltroNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblFiltroNombre.setText("Filtrar por Nombre: ");

        txtFiltroNombre.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscar.setBackground(new java.awt.Color(23, 117, 209));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnRestablecer.setBackground(new java.awt.Color(66, 66, 66));
        btnRestablecer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRestablecer.setForeground(new java.awt.Color(255, 255, 255));
        btnRestablecer.setText("Restablecer");
        btnRestablecer.addActionListener(this::btnRestablecerActionPerformed);

        lblUnidadMedida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));
        lblUnidadMedida.setText("Unidad de Medida:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Ingrediente", "Nombre", "Unidad de Medida", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnVovler.setBackground(new java.awt.Color(66, 66, 66));
        btnVovler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVovler.setForeground(new java.awt.Color(255, 255, 255));
        btnVovler.setText("Volver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblFiltroNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUnidadMedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestablecer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo2)
                        .addGap(282, 282, 282)))
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVovler)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroNombre)
                    .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnRestablecer)
                    .addComponent(lblUnidadMedida))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVovler)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.filtrarIngredientes();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        this.inicializarTablaLlena();
    }//GEN-LAST:event_btnRestablecerActionPerformed
    
    private void filtrarIngredientes(){
        try {
            String nombreFiltrado = txtFiltroNombre.getText().trim();
            UnidadMedida unidadMedida = (UnidadMedida) comboUnidadMedida.getSelectedItem();
            BuscadorIngredientesDTO filtrosIngrediente = new BuscadorIngredientesDTO(nombreFiltrado,unidadMedida);
            this.llenarTabla(ingredientesBO.consultarIngredientesFiltrados(filtrosIngrediente));
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al llenar tabla con los ingredientes: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void llenarComboUnidadMedida(){
        comboUnidadMedida.removeAllItems();
        comboUnidadMedida.addItem(UnidadMedida.PIEZA);
        comboUnidadMedida.addItem(UnidadMedida.GRAMOS);
        comboUnidadMedida.addItem(UnidadMedida.MILILITRO);
    }
    private void llenarTabla(List<Ingrediente> ingredientesActuales){
        this.ingredientesActuales = ingredientesActuales;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (Ingrediente ingrediente : ingredientesActuales) {
                modelo.addRow(new Object[]{
                ingrediente.getId(), ingrediente.getNombre(),ingrediente.getUnidadMedida(),ingrediente.getStock()
            });
        }
    }
    private void inicializarTablaLlena(){
        try {
            this.ingredientesActuales = ingredientesBO.consultarIngredientes();
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            for (Ingrediente ingrediente : ingredientesActuales) {
                modelo.addRow(new Object[]{
                ingrediente.getId(), ingrediente.getNombre(),ingrediente.getUnidadMedida(),ingrediente.getStock()
                });
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al llenar tabla con los ingredientes: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton btnVovler;
    private javax.swing.JComboBox<UnidadMedida> comboUnidadMedida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFiltroNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JTextField txtFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
