
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.Ingrediente;
import com.mycompany.restaurantenegocio.NegocioException;
import com.mycompany.restaurantenegocio.ObjetosBoDTO;
import interfaces.SeleccionIngredienteListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class FrmEliminarIngrediente extends javax.swing.JFrame implements SeleccionIngredienteListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEliminarIngrediente.class.getName());
    private final ObjetosBoDTO objetosBO;
    private Ingrediente ingredienteSeleccionado;
    /**
     * Creates new form FrmEliminarIngrediente
     * @param objetosBO
     */
    public FrmEliminarIngrediente(ObjetosBoDTO objetosBO) {
        this.objetosBO = objetosBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblNombreIngrediente = new javax.swing.JLabel();
        txtNombreIngrediente = new javax.swing.JTextField();
        lblUnidadMedida = new javax.swing.JLabel();
        txtUnidadMedida = new javax.swing.JTextField();
        lblStockActual = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnVovler = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(67, 82, 90));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Ingredientes -- Eliminar Ingrediente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(33, 84, 164));
        lblTitulo2.setText("Ingrediente a Eliminar");

        lblNombreIngrediente.setText("Nombre:");

        txtNombreIngrediente.setEditable(false);
        txtNombreIngrediente.setForeground(new java.awt.Color(0, 0, 0));

        lblUnidadMedida.setText("Unidad de Medida");

        txtUnidadMedida.setEditable(false);
        txtUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));

        lblStockActual.setText("Stock actual: ");

        txtStockActual.setEditable(false);
        txtStockActual.setForeground(new java.awt.Color(0, 0, 0));

        btnEliminar.setBackground(new java.awt.Color(200, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnVovler.setBackground(new java.awt.Color(66, 66, 66));
        btnVovler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVovler.setForeground(new java.awt.Color(255, 255, 255));
        btnVovler.setText("Volver");
        btnVovler.addActionListener(this::btnVovlerActionPerformed);

        jButton1.setBackground(new java.awt.Color(23, 117, 209));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUnidadMedida)
                    .addComponent(lblNombreIngrediente)
                    .addComponent(lblStockActual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(txtUnidadMedida)
                    .addComponent(txtStockActual))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVovler)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(252, 252, 252))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo2)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreIngrediente)
                    .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadMedida))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStockActual))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnVovler)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmBuscadorIngredientes frame = new FrmBuscadorIngredientes(objetosBO,this);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.eliminarIngrediente();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVovlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVovlerActionPerformed
        this.vaciarForm();
        this.dispose();
        FrmSeleccionarOpcionIngrediente frame = new FrmSeleccionarOpcionIngrediente(objetosBO);
        frame.setVisible(true);
    }//GEN-LAST:event_btnVovlerActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVovler;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreIngrediente;
    private javax.swing.JLabel lblStockActual;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JTextField txtNombreIngrediente;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
    
    private void eliminarIngrediente(){
        try {
            if (ingredienteSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Selecciona un ingrediente primero");
                return;
            }
            int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar el ingrediente?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );
            if(opcion == JOptionPane.YES_OPTION){
                Ingrediente ingredienteEliminado = objetosBO.getIngredientesBO().eliminarIngrediente(this.ingredienteSeleccionado.getId());
                String mensaje = """
                            ¡Ingrediente Eliminado Correctamente!
                             ID Ingrediente:  """+ingredienteEliminado.getId()+
                            "\n"+"Nombre: "+ingredienteEliminado.getNombre()+
                            "\n"+"Stock Inicial: "+ingredienteEliminado.getStock();
                JOptionPane.showMessageDialog(this, mensaje,"Ingrediente Eliminado Correctamente.",JOptionPane.INFORMATION_MESSAGE);
                vaciarForm();
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el ingrediente: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void vaciarForm(){
        txtNombreIngrediente.setText("");
        txtStockActual.setText("");
        txtUnidadMedida.setText("");
        this.ingredienteSeleccionado = null;
    }    
    @Override
    public void ingredienteSeleccionado(Ingrediente ingredienteSeleccionado) {
        this.ingredienteSeleccionado = ingredienteSeleccionado;
        txtNombreIngrediente.setText(ingredienteSeleccionado.getNombre());
        txtStockActual.setText(String.valueOf(ingredienteSeleccionado.getStock()));
        txtUnidadMedida.setText(ingredienteSeleccionado.getUnidadMedida().toString());
    }
}
