/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.Comanda;
import com.mycompany.restaurantedominio.EstadoComanda;
import com.mycompany.restaurantenegocio.NegocioException;
import com.mycompany.restaurantenegocio.ObjetosBoDTO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class FrmGestionComandas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(FrmGestionComandas.class.getName());
    
    private final ObjetosBoDTO objetosBO;
    private final boolean esMesero;
    private List<Comanda> listaActual = new ArrayList<>();
    
    public FrmGestionComandas(ObjetosBoDTO objetosBO, boolean esMesero) {
        this.objetosBO = objetosBO;
        this.esMesero = esMesero;
        initComponents();
        inicializarTabla();
        insertarMesasIniciales();
        inicializarComboEstado();
        cargarComandas();
    }
    
    private void insertarMesasIniciales() {
        try {
            objetosBO.getMesaBO().insertarMesasMasivo();
        } catch (NegocioException ex) {
            LOGGER.severe("Error al insertar mesas: " + ex.getMessage());
        }
    }
    
    private void inicializarTabla() {
        tblComandas.setModel(new DefaultTableModel(new String[]{ "Folio", "Fecha", "Hora", "Mesa", "Total ($)", "Cliente", "Estado" }, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
        });
        tblComandas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblComandas.getTableHeader().setReorderingAllowed(false);
    }
    
    private void inicializarComboEstado() {
        cmbEstado.removeAllItems();
        cmbEstado.addItem("Todos");
        for (EstadoComanda e : EstadoComanda.values()) {
            cmbEstado.addItem(e.toString());
        }
    }
    
    private void llenarTabla(List<Comanda> lista) {
        this.listaActual = lista;
        DefaultTableModel modelo = (DefaultTableModel) tblComandas.getModel();
        modelo.setRowCount(0);
        DateTimeFormatter fmtFecha = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        DateTimeFormatter fmtHora = DateTimeFormatter.ofPattern("HH:mm");
        for (Comanda c : lista) {
            modelo.addRow(new Object[]{
                c.getFolio(), c.getFechaHora().format(fmtFecha), c.getFechaHora().format(fmtHora), "Mesa " + c.getMesa().getNumeroMesa(), String.format("%.2f", c.getTotal()), c.getCliente().getNombre(), c.getEstado()
            });
        }
    }
    
    private Comanda getComandaSeleccionada() {
        int fila = tblComandas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una comanda de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return listaActual.get(fila);
    }
    
    private void cargarComandas() {
        try {
            llenarTabla(objetosBO.getComandaBO().obtenerTodos());
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buscarComandas() {
        try {
            String termino = txtBuscarFolio.getText().trim().toLowerCase();
            String estadoSel = (String) cmbEstado.getSelectedItem();
            List<Comanda> todas = objetosBO.getComandaBO().obtenerTodos();
            List<Comanda> filtradas = new ArrayList<>();
            for (Comanda c : todas) {
                boolean coincideFolio = termino.isEmpty() || c.getFolio().toLowerCase().contains(termino) || String.valueOf(c.getMesa().getNumeroMesa()).contains(termino);
                boolean coincideEstado = "Todos".equals(estadoSel) || c.getEstado().toString().equals(estadoSel);
                if (coincideFolio && coincideEstado) {
                    filtradas.add(c);
                }
            }
            llenarTabla(filtradas);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGestionComandas = new javax.swing.JLabel();
        lblBuscarFolioMesa = new javax.swing.JLabel();
        txtBuscarFolio = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComandas = new javax.swing.JTable();
        btnNuevaComanda = new javax.swing.JButton();
        btnInsertarMesas = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVerYEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        pnlGestionComandas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(191, 192, 192));

        lblGestionComandas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGestionComandas.setForeground(new java.awt.Color(33, 84, 164));
        lblGestionComandas.setText("Gestión de Comandas");

        lblBuscarFolioMesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBuscarFolioMesa.setText("Buscar folio / mesa:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setText("Estado:");

        cmbEstado.addActionListener(this::cmbEstadoActionPerformed);

        tblComandas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Fecha", "Hora", "Mesa", "Total ($)", "Cliente", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblComandas);

        btnNuevaComanda.setBackground(new java.awt.Color(0, 128, 0));
        btnNuevaComanda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevaComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaComanda.setText("+ Nueva Comanda");
        btnNuevaComanda.addActionListener(this::btnNuevaComandaActionPerformed);

        btnInsertarMesas.setBackground(new java.awt.Color(0, 128, 0));
        btnInsertarMesas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertarMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarMesas.setText("+ Insertar Mesas");
        btnInsertarMesas.addActionListener(this::btnInsertarMesasActionPerformed);

        btnBuscar.setBackground(new java.awt.Color(23, 117, 209));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnVerYEditar.setBackground(new java.awt.Color(23, 117, 209));
        btnVerYEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerYEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerYEditar.setText("Ver/Editar");
        btnVerYEditar.addActionListener(this::btnVerYEditarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(200, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnVolver.setBackground(new java.awt.Color(66, 66, 66));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        pnlGestionComandas.setBackground(new java.awt.Color(67, 82, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comandas — Gestion de Comandas");

        javax.swing.GroupLayout pnlGestionComandasLayout = new javax.swing.GroupLayout(pnlGestionComandas);
        pnlGestionComandas.setLayout(pnlGestionComandasLayout);
        pnlGestionComandasLayout.setHorizontalGroup(
            pnlGestionComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionComandasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212))
        );
        pnlGestionComandasLayout.setVerticalGroup(
            pnlGestionComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionComandasLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerYEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevaComanda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInsertarMesas))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGestionComandas)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBuscarFolioMesa)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBuscarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(lblEstado)))
                                .addGap(18, 18, 18)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(pnlGestionComandas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGestionComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGestionComandas)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaComanda)
                    .addComponent(btnInsertarMesas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarFolioMesa)
                    .addComponent(txtBuscarFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerYEditar)
                    .addComponent(btnCancelar)
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        buscarComandas();
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnNuevaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaComandaActionPerformed
        FrmNuevaComanda frm = new FrmNuevaComanda(objetosBO);
        frm.setVisible(true);
        frm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                cargarComandas();
            }
        });
    }//GEN-LAST:event_btnNuevaComandaActionPerformed

    private void btnInsertarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarMesasActionPerformed
        try {
            objetosBO.getMesaBO().insertarMesasMasivo();
            List<com.mycompany.restaurantedominio.Mesa> mesas = objetosBO.getMesaBO().obtenerTodos();
            JOptionPane.showMessageDialog(this, "20 mesas insertadas exitosamente. Total de mesas: " + mesas.size(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertarMesasActionPerformed

    private void btnVerYEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerYEditarActionPerformed
        Comanda sel = getComandaSeleccionada();
        if (sel == null) return;
        FrmNuevaComanda frm = new FrmNuevaComanda(objetosBO, sel);
        frm.setVisible(true);
        frm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                cargarComandas();
            }
        });
    }//GEN-LAST:event_btnVerYEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Comanda sel = getComandaSeleccionada();
        if (sel == null) return;
        if (sel.getEstado() == EstadoComanda.ENTREGADA ||
            sel.getEstado() == EstadoComanda.CANCELADA) {
            JOptionPane.showMessageDialog(this, "Solo se pueden cancelar comandas Abiertas.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas cancelar la comanda " + sel.getFolio() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                objetosBO.getComandaBO().cancelar(sel.getId());
                objetosBO.getMesaBO().actualizarDisponibilidad(sel.getMesa().getId());
                JOptionPane.showMessageDialog(this, "Comanda cancelada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarComandas();
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (esMesero) {
            // Mesero simplemente cierra
            dispose();
        } else {
            // Administrador regresa al menú principal
            FrmGestionDeComandas frame = new FrmGestionDeComandas(objetosBO);
            frame.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarComandas();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertarMesas;
    private javax.swing.JButton btnNuevaComanda;
    private javax.swing.JButton btnVerYEditar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarFolioMesa;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGestionComandas;
    private javax.swing.JPanel pnlGestionComandas;
    private javax.swing.JTable tblComandas;
    private javax.swing.JTextField txtBuscarFolio;
    // End of variables declaration//GEN-END:variables
}

