/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.ClienteFrecuente;
import com.mycompany.restaurantenegocio.ClienteBO;
import com.mycompany.restaurantenegocio.IClienteBO;
import com.mycompany.restaurantenegocio.IComandaBO;
import com.mycompany.restaurantenegocio.IMesaBO;
import com.mycompany.restaurantenegocio.IProductoBO;
import com.mycompany.restaurantenegocio.IReporteClientesFrecuentesBO;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class FrmGestionDeComandas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(FrmGestionDeComandas.class.getName());
    private final ClienteFrecuente cliente;
    private final IClienteBO clienteBO;
    private final IComandaBO comandaBO;
    private final IMesaBO mesaBO;
    private final IProductoBO productoBO;
    private final IReporteClientesFrecuentesBO reporteBO;

    /**
     * Creates new form FrmGestionDeComandas
     */
    public FrmGestionDeComandas(IComandaBO comandaBO, IMesaBO mesaBO, IProductoBO productoBO, IClienteBO clienteBO, ClienteFrecuente cliente, IReporteClientesFrecuentesBO reporteBO) {
        this.reporteBO = reporteBO;
        this.cliente = cliente;
        this.clienteBO = clienteBO;
        this.comandaBO = comandaBO;
        this.mesaBO = mesaBO;
        this.productoBO = productoBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGestionComandas = new javax.swing.JPanel();
        lblSistemaGestionComandas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnComandas = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnIngredientes = new javax.swing.JButton();
        btnClientesFrecuentes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(191, 192, 192));

        pnlGestionComandas.setBackground(new java.awt.Color(67, 82, 90));
        pnlGestionComandas.setPreferredSize(new java.awt.Dimension(663, 32));

        lblSistemaGestionComandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSistemaGestionComandas.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemaGestionComandas.setText("Sistema de Gestión de Comandas ");

        javax.swing.GroupLayout pnlGestionComandasLayout = new javax.swing.GroupLayout(pnlGestionComandas);
        pnlGestionComandas.setLayout(pnlGestionComandasLayout);
        pnlGestionComandasLayout.setHorizontalGroup(
            pnlGestionComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionComandasLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lblSistemaGestionComandas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGestionComandasLayout.setVerticalGroup(
            pnlGestionComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionComandasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSistemaGestionComandas)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 84, 164));
        jLabel1.setText("Sistema de Gestión de Comandas");

        btnComandas.setBackground(new java.awt.Color(12, 70, 160));
        btnComandas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComandas.setForeground(new java.awt.Color(255, 255, 255));
        btnComandas.setText("Comandas");
        btnComandas.addActionListener(this::btnComandasActionPerformed);

        btnProductos.setBackground(new java.awt.Color(23, 117, 209));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);

        btnIngredientes.setBackground(new java.awt.Color(16, 109, 88));
        btnIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        btnIngredientes.setText("Ingredientes");
        btnIngredientes.addActionListener(this::btnIngredientesActionPerformed);

        btnClientesFrecuentes.setBackground(new java.awt.Color(0, 128, 0));
        btnClientesFrecuentes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClientesFrecuentes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientesFrecuentes.setText("Clientes Frecuentes");
        btnClientesFrecuentes.addActionListener(this::btnClientesFrecuentesActionPerformed);

        btnReportes.setBackground(new java.awt.Color(255, 140, 0));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGestionComandas, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngredientes)
                        .addGap(18, 18, 18)
                        .addComponent(btnClientesFrecuentes)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlGestionComandas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClientesFrecuentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasActionPerformed
        FrmGestionComandas frame = new FrmGestionComandas(comandaBO, mesaBO, productoBO, false, clienteBO, reporteBO);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComandasActionPerformed

    private void btnClientesFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesFrecuentesActionPerformed
       FrmGestionClientes frame = new FrmGestionClientes(cliente, (ClienteBO) clienteBO, comandaBO, mesaBO, productoBO, reporteBO);
       frame.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnClientesFrecuentesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngredientesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FrmGeneracionReportes frame = new FrmGeneracionReportes(reporteBO, comandaBO, mesaBO, productoBO, clienteBO);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesFrecuentes;
    private javax.swing.JButton btnComandas;
    private javax.swing.JButton btnIngredientes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSistemaGestionComandas;
    private javax.swing.JPanel pnlGestionComandas;
    // End of variables declaration//GEN-END:variables
}
