/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.ClienteFrecuente;
import com.mycompany.restaurantenegocio.IClienteBO;
import com.mycompany.restaurantenegocio.IComandaBO;
import com.mycompany.restaurantenegocio.IMesaBO;
import com.mycompany.restaurantenegocio.IProductoBO;
import com.mycompany.restaurantenegocio.IReporteClientesFrecuentesBO;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class FrmGeneracionReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(FrmGeneracionReportes.class.getName());
    
    private final IReporteClientesFrecuentesBO reporteBO;
    private final IComandaBO comandaBO;
    private final IMesaBO mesaBO;
    private final IProductoBO productoBO;
    private final IClienteBO clienteBO;

    /**
     * Creates new form FrmGeneracionReportes
     */
    public FrmGeneracionReportes(IReporteClientesFrecuentesBO reporteBO, IComandaBO comandaBO, IMesaBO mesaBO, IProductoBO productoBO, IClienteBO clienteBO) {
        this.reporteBO = reporteBO;
        this.comandaBO = comandaBO;
        this.mesaBO = mesaBO;
        this.productoBO = productoBO;
        this.clienteBO = clienteBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporteComandas = new javax.swing.JButton();
        lblGeneracionReportes = new javax.swing.JLabel();
        btnReportesClientes = new javax.swing.JButton();
        pnlReporteSeleccion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(191, 192, 192));

        btnReporteComandas.setBackground(new java.awt.Color(33, 84, 164));
        btnReporteComandas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteComandas.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteComandas.setText("Reporte de Comandas");
        btnReporteComandas.addActionListener(this::btnReporteComandasActionPerformed);

        lblGeneracionReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGeneracionReportes.setForeground(new java.awt.Color(33, 84, 164));
        lblGeneracionReportes.setText("Generacion de Reportes");

        btnReportesClientes.setBackground(new java.awt.Color(16, 109, 88));
        btnReportesClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportesClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportesClientes.setText("Reporte de Clientes");
        btnReportesClientes.addActionListener(this::btnReportesClientesActionPerformed);

        pnlReporteSeleccion.setBackground(new java.awt.Color(67, 82, 90));
        pnlReporteSeleccion.setPreferredSize(new java.awt.Dimension(344, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes--Seleccion");

        javax.swing.GroupLayout pnlReporteSeleccionLayout = new javax.swing.GroupLayout(pnlReporteSeleccion);
        pnlReporteSeleccion.setLayout(pnlReporteSeleccionLayout);
        pnlReporteSeleccionLayout.setHorizontalGroup(
            pnlReporteSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporteSeleccionLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReporteSeleccionLayout.setVerticalGroup(
            pnlReporteSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteSeleccionLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        btnVolver.setBackground(new java.awt.Color(66, 66, 66));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReporteSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnReporteComandas)
                                .addGap(44, 44, 44)
                                .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(lblGeneracionReportes)))
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlReporteSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGeneracionReportes)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteComandas)
                    .addComponent(btnReportesClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteComandasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteComandasActionPerformed

    private void btnReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesClientesActionPerformed
        FrmReporteClientesFrecuentes frame = new FrmReporteClientesFrecuentes(reporteBO, clienteBO, comandaBO, mesaBO, productoBO);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReportesClientesActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmGestionDeComandas frame = new FrmGestionDeComandas(comandaBO, mesaBO, productoBO, clienteBO, null, reporteBO);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteComandas;
    private javax.swing.JButton btnReportesClientes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGeneracionReportes;
    private javax.swing.JPanel pnlReporteSeleccion;
    // End of variables declaration//GEN-END:variables
}
