/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mycompany.restaurantedtos.ReporteClientesFrecuentesDTO;
import com.mycompany.restaurantenegocio.IClienteBO;
import com.mycompany.restaurantenegocio.IComandaBO;
import com.mycompany.restaurantenegocio.IMesaBO;
import com.mycompany.restaurantenegocio.IProductoBO;
import com.mycompany.restaurantenegocio.IReporteClientesFrecuentesBO;
import com.mycompany.restaurantenegocio.NegocioException;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class FrmReporteClientesFrecuentes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(FrmReporteClientesFrecuentes.class.getName());
    
    private final IReporteClientesFrecuentesBO reporteBO;
    private final IClienteBO clienteBO;
    private final IComandaBO comandaBO;
    private final IMesaBO mesaBO;
    private final IProductoBO productoBO;
    private List<ReporteClientesFrecuentesDTO> listaActual = new ArrayList<>();
    
    public FrmReporteClientesFrecuentes(IReporteClientesFrecuentesBO reporteBO, IClienteBO clienteBO, IComandaBO comandaBO, IMesaBO mesaBO, IProductoBO productoBO) {
        this.reporteBO = reporteBO;
        this.clienteBO = clienteBO;
        this.comandaBO = comandaBO;
        this.mesaBO = mesaBO;
        this.productoBO = productoBO;
        initComponents();
        inicializarTabla();
        cargarReporte();
    }
    
    private void inicializarTabla() {
        jTable1.setModel(new DefaultTableModel(
            new String[]{"Nombre", "Visitas", "Total ($)", "Última Visita", "Puntos"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) { 
                return false; 
            }
        });
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    private void cargarReporte() {
        try {
            llenarTabla(reporteBO.obtenerReporte());
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void llenarTabla(java.util.List<ReporteClientesFrecuentesDTO> lista) {
        this.listaActual = lista;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (ReporteClientesFrecuentesDTO dto : lista) {
            modelo.addRow(new Object[]{
                dto.getNombre(), dto.getNumVisitas(), String.format("%.2f", dto.getTotalGastado()), dto.getFechaUltimaVisita() != null ? dto.getFechaUltimaVisita().toString() : "Sin visitas", (int)(dto.getTotalGastado() / 20)
            });
        }
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFiltrarPorNombres = new javax.swing.JLabel();
        txtFiltroPorNombre = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        txtVisitasMinimas = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnTodosLosClientesPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnExportarClienteSeleccionado = new javax.swing.JButton();
        pnlReporteClientesFrecuente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblReportesClientesFrecuentes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(191, 192, 192));

        lblFiltrarPorNombres.setText("Filtrar por Nombre:");

        txtFiltroPorNombre.addActionListener(this::txtFiltroPorNombreActionPerformed);

        lbl.setText("Visitas Minimas:");

        txtVisitasMinimas.setCaretColor(new java.awt.Color(255, 255, 255));

        btnFiltrar.setBackground(new java.awt.Color(23, 117, 209));
        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(this::btnFiltrarActionPerformed);

        btnTodosLosClientesPDF.setBackground(new java.awt.Color(0, 100, 0));
        btnTodosLosClientesPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTodosLosClientesPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnTodosLosClientesPDF.setText("Exportar Todos Clientes PDF");
        btnTodosLosClientesPDF.addActionListener(this::btnTodosLosClientesPDFActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Visitas", "Total ($)", "Última Visita", "Puntos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnVolver.setBackground(new java.awt.Color(66, 66, 66));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        btnExportarClienteSeleccionado.setBackground(new java.awt.Color(0, 100, 0));
        btnExportarClienteSeleccionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExportarClienteSeleccionado.setForeground(new java.awt.Color(255, 255, 255));
        btnExportarClienteSeleccionado.setText("ExportarPDF");
        btnExportarClienteSeleccionado.addActionListener(this::btnExportarClienteSeleccionadoActionPerformed);

        pnlReporteClientesFrecuente.setBackground(new java.awt.Color(67, 82, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes--ClientesFrecuentes");

        javax.swing.GroupLayout pnlReporteClientesFrecuenteLayout = new javax.swing.GroupLayout(pnlReporteClientesFrecuente);
        pnlReporteClientesFrecuente.setLayout(pnlReporteClientesFrecuenteLayout);
        pnlReporteClientesFrecuenteLayout.setHorizontalGroup(
            pnlReporteClientesFrecuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteClientesFrecuenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(283, 283, 283))
        );
        pnlReporteClientesFrecuenteLayout.setVerticalGroup(
            pnlReporteClientesFrecuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReporteClientesFrecuenteLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        lblReportesClientesFrecuentes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReportesClientesFrecuentes.setForeground(new java.awt.Color(33, 84, 164));
        lblReportesClientesFrecuentes.setText("Reporte de Clientes Frecuentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReporteClientesFrecuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblFiltrarPorNombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltroPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVisitasMinimas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportarClienteSeleccionado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnTodosLosClientesPDF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(lblReportesClientesFrecuentes)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlReporteClientesFrecuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportesClientesFrecuentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarPorNombres)
                    .addComponent(txtFiltroPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl)
                    .addComponent(txtVisitasMinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportarClienteSeleccionado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTodosLosClientesPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroPorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroPorNombreActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        try {
            String nombre = txtFiltroPorNombre.getText().trim();
            String visitasStr = txtVisitasMinimas.getText().trim();

            if (!nombre.isEmpty() && !visitasStr.isEmpty()) {
                // Filtra por ambos
                List<ReporteClientesFrecuentesDTO> porNombre = reporteBO.filtrarPorNombre(nombre);
                List<ReporteClientesFrecuentesDTO> filtrados = new ArrayList<>();
                int minVisitas = Integer.parseInt(visitasStr);
                for (ReporteClientesFrecuentesDTO dto : porNombre) {
                    if (dto.getNumVisitas() >= minVisitas) {
                        filtrados.add(dto);
                    }
                }
                llenarTabla(filtrados);
            } else if (!nombre.isEmpty()) {
                llenarTabla(reporteBO.filtrarPorNombre(nombre));
            } else if (!visitasStr.isEmpty()) {
                llenarTabla(reporteBO.filtrarPorMinimoVisitas(Integer.parseInt(visitasStr)));
            } else {
                cargarReporte();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Las visitas mínimas deben ser un número entero.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnTodosLosClientesPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosLosClientesPDFActionPerformed
        if (listaActual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay datos para exportar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Elegir dónde guardar
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar PDF");
        fileChooser.setSelectedFile(new File("ReporteClientesFrecuentes.pdf"));
        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            if (!ruta.endsWith(".pdf")) ruta += ".pdf";

            try {
                Document doc = new Document();
                PdfWriter.getInstance(doc, new FileOutputStream(ruta));
                doc.open();

                // Encabezado
                Font fontTitulo = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
                Font fontNormal = new Font( Font.FontFamily.HELVETICA, 10);

                doc.add(new Paragraph("Reporte de Clientes Frecuentes", fontTitulo));
                doc.add(new Paragraph("Fecha de generación: " + java.time.LocalDate.now().toString(), fontNormal));
                doc.add(Chunk.NEWLINE);

                // Tabla
                PdfPTable tabla = new PdfPTable(5);
                tabla.setWidthPercentage(100);

                // Encabezados de tabla
                String[] columnas = {"Nombre", "Visitas", "Total ($)", "Última Visita", "Puntos"};
                for (String col : columnas) {
                    PdfPCell celda = new PdfPCell(new Phrase(col, new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD)));
                    celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
                    tabla.addCell(celda);
                }

                // Datos
                for (ReporteClientesFrecuentesDTO dto : listaActual) {
                    tabla.addCell(new Phrase(dto.getNombre(), fontNormal));
                    tabla.addCell(new Phrase(String.valueOf(dto.getNumVisitas()), fontNormal));
                    tabla.addCell(new Phrase(String.format("%.2f", dto.getTotalGastado()), fontNormal));
                    tabla.addCell(new Phrase(dto.getFechaUltimaVisita() != null ? dto.getFechaUltimaVisita().toString() : "Sin visitas", fontNormal));
                    tabla.addCell(new Phrase(String.valueOf((int)(dto.getTotalGastado() / 20)), fontNormal));
                }

                doc.add(tabla);
                doc.close();

                JOptionPane.showMessageDialog(this, "PDF generado exitosamente en:\n" + ruta, "Éxito", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al generar PDF: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTodosLosClientesPDFActionPerformed

    private void btnExportarClienteSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarClienteSeleccionadoActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ReporteClientesFrecuentesDTO dto = listaActual.get(fila);

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar PDF");
        fileChooser.setSelectedFile(new File("ReporteCliente_" + dto.getNombre() + ".pdf"));
        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            if (!ruta.endsWith(".pdf")) ruta += ".pdf";
            try {
                Document doc = new Document();
                PdfWriter.getInstance(doc, new FileOutputStream(ruta));
                doc.open();

                // Encabezado
                Font fontTitulo = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
                Font fontNormal = new Font(Font.FontFamily.HELVETICA, 10);

                doc.add(new Paragraph("Reporte de Cliente Frecuente", fontTitulo));
                doc.add(new Paragraph("Fecha de generación: " + java.time.LocalDate.now().toString(), fontNormal));
                doc.add(Chunk.NEWLINE);

                // Tabla
                PdfPTable tabla = new PdfPTable(5);
                tabla.setWidthPercentage(100);

                // Encabezados
                String[] columnas = {"Nombre", "Visitas", "Total ($)", "Última Visita", "Puntos"};
                for (String col : columnas) {
                    PdfPCell celda = new PdfPCell(new Phrase(col, new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD)));
                    celda.setBackgroundColor(BaseColor.LIGHT_GRAY);
                    tabla.addCell(celda);
                }

                // Solo el cliente seleccionado
                tabla.addCell(new Phrase(dto.getNombre(), fontNormal));
                tabla.addCell(new Phrase(String.valueOf(dto.getNumVisitas()), fontNormal));
                tabla.addCell(new Phrase(String.format("%.2f", dto.getTotalGastado()), fontNormal));
                tabla.addCell(new Phrase(dto.getFechaUltimaVisita() != null ? dto.getFechaUltimaVisita().toString() : "Sin visitas", fontNormal));
                tabla.addCell(new Phrase(String.valueOf((int)(dto.getTotalGastado() / 20)), fontNormal));

                doc.add(tabla);
                doc.close();

                JOptionPane.showMessageDialog(this, "PDF generado exitosamente en:\n" + ruta, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al generar PDF: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportarClienteSeleccionadoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FrmGeneracionReportes frame = new FrmGeneracionReportes(reporteBO, comandaBO, mesaBO, productoBO, clienteBO);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarClienteSeleccionado;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnTodosLosClientesPDF;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblFiltrarPorNombres;
    private javax.swing.JLabel lblReportesClientesFrecuentes;
    private javax.swing.JPanel pnlReporteClientesFrecuente;
    private javax.swing.JTextField txtFiltroPorNombre;
    private javax.swing.JTextField txtVisitasMinimas;
    // End of variables declaration//GEN-END:variables
}
