
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantedominio.Ingrediente;
import com.mycompany.restaurantedtos.NuevoIngredienteDTO;
import com.mycompany.restaurantedtos.UnidadMedida;
import com.mycompany.restaurantenegocio.NegocioException;
import com.mycompany.restaurantenegocio.ObjetosBoDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class FrmRegistrarNuevoIngrediente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistrarNuevoIngrediente.class.getName());
    private final ObjetosBoDTO objetosBO;
    /**
     * Creates new form FrmRegistrarNuevoIngrediente
     * @param objetosBO
     */
    public FrmRegistrarNuevoIngrediente(ObjetosBoDTO objetosBO) {
        this.objetosBO = objetosBO;
        initComponents();
        llenarComboUnidadMedida();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreIngrediente = new javax.swing.JLabel();
        txtNombreIngrediente = new javax.swing.JTextField();
        lblStockInicial = new javax.swing.JLabel();
        txtStockInicial = new javax.swing.JTextField();
        lblUnidadMedida = new javax.swing.JLabel();
        comboUnidadMedida = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTItulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreIngrediente.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreIngrediente.setText("Nombre del Ingrediente: ");

        txtNombreIngrediente.setForeground(new java.awt.Color(0, 0, 0));

        lblStockInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStockInicial.setForeground(new java.awt.Color(0, 0, 0));
        lblStockInicial.setText("Stock Inicial: ");

        txtStockInicial.setForeground(new java.awt.Color(0, 0, 0));

        lblUnidadMedida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnidadMedida.setForeground(new java.awt.Color(0, 0, 0));
        lblUnidadMedida.setText("Unidad de Medida: ");

        btnRegistrar.setBackground(new java.awt.Color(0, 128, 0));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnVolver.setBackground(new java.awt.Color(66, 66, 66));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jPanel2.setBackground(new java.awt.Color(67, 82, 90));

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("Ingredientes — Nuevo Ingrediente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(lblTitulo2)
                .addGap(283, 283, 283))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblTItulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTItulo.setForeground(new java.awt.Color(33, 84, 164));
        lblTItulo.setText("Registro De Ingrediente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreIngrediente)
                            .addComponent(lblStockInicial))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreIngrediente)
                            .addComponent(txtStockInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addComponent(lblUnidadMedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(lblTItulo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTItulo)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreIngrediente)
                    .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadMedida)
                    .addComponent(comboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockInicial)
                    .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        this.registrarNuevoIngrediente();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.vaciarForm();
        this.dispose();
        FrmSeleccionarOpcionIngrediente frame = new FrmSeleccionarOpcionIngrediente(objetosBO);
        frame.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed
    
    private void llenarComboUnidadMedida(){
        comboUnidadMedida.removeAllItems();
        comboUnidadMedida.addItem(UnidadMedida.PIEZA);
        comboUnidadMedida.addItem(UnidadMedida.GRAMOS);
        comboUnidadMedida.addItem(UnidadMedida.MILILITRO);
    }
    
    private void registrarNuevoIngrediente(){
        try{
            if(txtNombreIngrediente.getText().trim().isEmpty() || txtStockInicial.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this,"Error en los datos del FORM.\n No deben estar vacios los campos de texto.","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            String nombre = txtNombreIngrediente.getText();
            Integer stockInicial = Integer.valueOf(txtStockInicial.getText());
            UnidadMedida unidadMedida = (UnidadMedida) comboUnidadMedida.getSelectedItem();
            NuevoIngredienteDTO ingrediente = new NuevoIngredienteDTO(nombre.trim(),stockInicial,unidadMedida);
            Ingrediente ingredienteRegistrado = objetosBO.getIngredientesBO().registrarIngrediente(ingrediente);
            String mensaje = """
                            ¡Ingrediente Registrado Correctamente!
                             ID Ingrediente:  """+ingredienteRegistrado.getId()+
                            "\n"+"Nombre: "+ingredienteRegistrado.getNombre()+
                            "\n"+"Stock Inicial: "+ingredienteRegistrado.getStock();
            JOptionPane.showMessageDialog(this, mensaje, 
            "Ingrediente Registrado Correctamente.", 
            JOptionPane.INFORMATION_MESSAGE);
            vaciarForm();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Error al registrar el ingrediente.\n Se espera un numero enetero positivo. ","ERROR",JOptionPane.ERROR_MESSAGE);
        } 
        catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al registrar el ingrediente: " + ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void vaciarForm(){
        txtNombreIngrediente.setText("");
        txtStockInicial.setText("");
        comboUnidadMedida.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<UnidadMedida> comboUnidadMedida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreIngrediente;
    private javax.swing.JLabel lblStockInicial;
    private javax.swing.JLabel lblTItulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JTextField txtNombreIngrediente;
    private javax.swing.JTextField txtStockInicial;
    // End of variables declaration//GEN-END:variables
}
