
package com.mycompany.restaurantepresentacion;

import com.mycompany.restaurantenegocio.ObjetosBoDTO;
import interfaces.SeleccionIngredienteListener;

/**
 *
 * @author Julian
 */
public class FrmSeleccionarOpcionIngrediente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSeleccionarOpcionIngrediente.class.getName());
    private final ObjetosBoDTO objetosBO;
    /**
     * Creates new form FrmSeleccionarOpcionIngrediente
     */
    public FrmSeleccionarOpcionIngrediente(ObjetosBoDTO objetosBO) {
        this.objetosBO = objetosBO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVovler = new javax.swing.JButton();
        lblTitulo2 = new javax.swing.JLabel();
        btnAgregarStock = new javax.swing.JButton();
        btnEliminarIngrediente = new javax.swing.JButton();
        btnRegistrarNuevoIngrediente = new javax.swing.JButton();
        btnBuscadorIngredientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(67, 82, 90));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Ingredientes -- Opciones Ingredientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(156, 156, 156))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(lblTitulo))
        );

        btnVovler.setBackground(new java.awt.Color(66, 66, 66));
        btnVovler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVovler.setForeground(new java.awt.Color(255, 255, 255));
        btnVovler.setText("Volver");
        btnVovler.addActionListener(this::btnVovlerActionPerformed);

        lblTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(33, 84, 164));
        lblTitulo2.setText("Seleccionar Opción");

        btnAgregarStock.setBackground(new java.awt.Color(255, 140, 0));
        btnAgregarStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarStock.setText("Agregar Stock");
        btnAgregarStock.addActionListener(this::btnAgregarStockActionPerformed);

        btnEliminarIngrediente.setBackground(new java.awt.Color(200, 0, 0));
        btnEliminarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarIngrediente.setText("Eliminar Ingrediente");
        btnEliminarIngrediente.addActionListener(this::btnEliminarIngredienteActionPerformed);

        btnRegistrarNuevoIngrediente.setBackground(new java.awt.Color(0, 128, 0));
        btnRegistrarNuevoIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarNuevoIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarNuevoIngrediente.setText("Registrar Ingrediente");
        btnRegistrarNuevoIngrediente.addActionListener(this::btnRegistrarNuevoIngredienteActionPerformed);

        btnBuscadorIngredientes.setBackground(new java.awt.Color(52, 152, 219));
        btnBuscadorIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscadorIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscadorIngredientes.setText("Buscador Ingredientes");
        btnBuscadorIngredientes.addActionListener(this::btnBuscadorIngredientesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVovler))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarNuevoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(btnAgregarStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscadorIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo2)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo2)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarNuevoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscadorIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(btnVovler)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        FrmAgregarStockIngrediente frame = new FrmAgregarStockIngrediente(objetosBO);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIngredienteActionPerformed
        FrmEliminarIngrediente frame = new FrmEliminarIngrediente(objetosBO);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarIngredienteActionPerformed

    private void btnRegistrarNuevoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoIngredienteActionPerformed
        FrmRegistrarNuevoIngrediente frame = new FrmRegistrarNuevoIngrediente(objetosBO);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarNuevoIngredienteActionPerformed

    private void btnBuscadorIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscadorIngredientesActionPerformed
        FrmBuscadorIngredientes frame = new FrmBuscadorIngredientes(objetosBO);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscadorIngredientesActionPerformed

    private void btnVovlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVovlerActionPerformed
        FrmGestionDeComandas frame = new FrmGestionDeComandas(objetosBO);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVovlerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnBuscadorIngredientes;
    private javax.swing.JButton btnEliminarIngrediente;
    private javax.swing.JButton btnRegistrarNuevoIngrediente;
    private javax.swing.JButton btnVovler;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    // End of variables declaration//GEN-END:variables
}
